version: '3.4'

services:
  testwebapp:
    image: testwebapp
    build:
      context: src/azure-cli/azure/cli/command_modules/appservice/sample-repo-for-deployment-test
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
